namespace AfterApply.Application.Identity;

public interface ITokenService
{
    (string AccessToken, DateTimeOffset ExpiresAt) CreateAccessToken(Guid userId, string email);

    string GenerateRefreshToken();

    string HashRefreshToken(string refreshToken);

    string GeneratePersonalAccessToken();

    string HashPersonalAccessToken(string token);

    /// <summary>The half of an extension pairing handshake that stays inside the extension. Not a
    /// personal access token and deliberately not generated by the same method: it authenticates
    /// nothing but the poll for one specific pairing, carries no prefix (it never travels in an
    /// Authorization header) and dies with the request.</summary>
    string GenerateExtensionPairingSecret();

    string HashExtensionPairingSecret(string secret);

    /// <summary>Short-lived, signed carrier for a verified Google identity between the two steps of a
    /// Google sign-up (see GoogleSignupPrefill): the authorization code is single-use and already
    /// spent by the time the user sees the consent form, so this is what proves, on the second
    /// request, that the identity really came from Google.</summary>
    string CreateGoogleSignupToken(GoogleIdentity identity);

    /// <summary>Null for anything that is not an unexpired token from
    /// <see cref="CreateGoogleSignupToken"/> — including one of our own access tokens. Async only
    /// because the JWT library's validation entry point is; creating a token stays synchronous.</summary>
    Task<GoogleIdentity?> ValidateGoogleSignupTokenAsync(string token);

    /// <summary>Same role as <see cref="CreateGoogleSignupToken"/>, for a LinkedIn sign-up. A
    /// separate pair of methods rather than a shared generic one: <see cref="LinkedInIdentity"/>'s
    /// email is nullable (LinkedIn's OpenID Connect response makes it optional) where
    /// <see cref="GoogleIdentity"/>'s is not, so the two claim sets aren't quite interchangeable.</summary>
    string CreateLinkedInSignupToken(LinkedInIdentity identity);

    /// <summary>Null for anything that is not an unexpired token from
    /// <see cref="CreateLinkedInSignupToken"/> — including one of our own access tokens.</summary>
    Task<LinkedInIdentity?> ValidateLinkedInSignupTokenAsync(string token);

    /// <summary>Same role as <see cref="CreateLinkedInSignupToken"/>, for a GitHub sign-up.
    /// <see cref="GitHubIdentity"/> gets its own pair for the same reason LinkedIn does: its email is
    /// nullable and the audience must not be interchangeable with another provider's, or a signup
    /// token minted for one identity could create an account under another.</summary>
    string CreateGitHubSignupToken(GitHubIdentity identity);

    /// <summary>Null for anything that is not an unexpired token from
    /// <see cref="CreateGitHubSignupToken"/> — including one of our own access tokens, and including
    /// a Google or LinkedIn signup token signed with the very same key.</summary>
    Task<GitHubIdentity?> ValidateGitHubSignupTokenAsync(string token);
}
