using System.Security.Claims;
using AfterApply.Api.Extensions;
using AfterApply.Application.Notifications;
using AfterApply.Application.Notifications.Contracts;

namespace AfterApply.Api.Endpoints;

public static class ReminderEndpoints
{
    public static IEndpointRouteBuilder MapReminderEndpoints(this IEndpointRouteBuilder app)
    {
        var group = app.MapGroup("/api/reminders").WithTags("Reminders").RequireAuthorization()
            .ProducesProblem(StatusCodes.Status401Unauthorized);

        group.MapGet("/", async (ClaimsPrincipal user, IReminderService service, CancellationToken cancellationToken) =>
            Results.Ok(await service.GetActiveRemindersAsync(user.GetUserId(), cancellationToken)))
            .WithSummary("List the current user's active reminders")
            .WithDescription("Follow-up and ghosting reminders generated by a daily scan of the user's applications.")
            .Produces<IReadOnlyList<ReminderResponse>>();

        group.MapPost("/{id:guid}/dismiss", async (Guid id, ClaimsPrincipal user, IReminderService service, CancellationToken cancellationToken) =>
        {
            var dismissed = await service.DismissAsync(user.GetUserId(), id, cancellationToken);
            return dismissed ? Results.NoContent() : Results.NotFound();
        })
            .WithSummary("Dismiss a reminder")
            .Produces(StatusCodes.Status204NoContent)
            .ProducesProblem(StatusCodes.Status404NotFound);

        group.MapPost("/{id:guid}/follow-up", async (Guid id, ClaimsPrincipal user, IReminderService service, CancellationToken cancellationToken) =>
        {
            var marked = await service.MarkFollowedUpAsync(user.GetUserId(), id, cancellationToken);
            return marked ? Results.NoContent() : Results.NotFound();
        })
            .WithSummary("Answer a reminder with \"I followed up\"")
            .WithDescription("Records a FollowUpSent event on the application and closes the reminder. 404 when the " +
                             "reminder is not the caller's or is already closed.")
            .Produces(StatusCodes.Status204NoContent)
            .ProducesProblem(StatusCodes.Status404NotFound);

        return app;
    }
}
