using System.Security.Claims;
using AfterApply.Api.Extensions;
using AfterApply.Application.Applications;
using AfterApply.Application.Applications.Contracts;
using AfterApply.Application.Localization;
using AfterApply.Application.Notifications;
using AfterApply.Application.Notifications.Contracts;
using Microsoft.Extensions.Localization;

namespace AfterApply.Api.Endpoints;

public static class ReminderEndpoints
{
    public static IEndpointRouteBuilder MapReminderEndpoints(this IEndpointRouteBuilder app)
    {
        var group = app.MapGroup("/api/reminders").WithTags("Reminders").RequireAuthorization()
            .ProducesProblem(StatusCodes.Status401Unauthorized);

        group.MapGet("/", async ([AsParameters] GetRemindersQuery query, ClaimsPrincipal user, IReminderService service,
                CancellationToken cancellationToken) =>
            Results.Ok(await service.GetActiveRemindersAsync(user.GetUserId(), query, cancellationToken)))
            .WithValidation<GetRemindersQuery>()
            .WithSummary("List the current user's active reminders")
            .WithDescription("Follow-up and ghosting reminders generated by a daily scan of the user's applications. " +
                             "Paged, longest-waiting first; PageSize defaults to the dashboard card's five rows.")
            .Produces<PagedResult<ReminderResponse>>();

        group.MapPost("/{id:guid}/dismiss", async (Guid id, ClaimsPrincipal user, IReminderService service, CancellationToken cancellationToken) =>
        {
            var dismissed = await service.DismissAsync(user.GetUserId(), id, cancellationToken);
            return dismissed ? Results.NoContent() : Results.NotFound();
        })
            .WithSummary("Dismiss a reminder")
            .Produces(StatusCodes.Status204NoContent)
            .ProducesProblem(StatusCodes.Status404NotFound);

        group.MapPost("/{id:guid}/follow-up", async (Guid id, ClaimsPrincipal user, IReminderService service, CancellationToken cancellationToken) =>
        {
            var marked = await service.MarkFollowedUpAsync(user.GetUserId(), id, cancellationToken);
            return marked ? Results.NoContent() : Results.NotFound();
        })
            .WithSummary("Answer a reminder with \"I followed up\"")
            .WithDescription("Records a FollowUpSent event on the application and closes the reminder. 404 when the " +
                             "reminder is not the caller's or is already closed.")
            .Produces(StatusCodes.Status204NoContent)
            .ProducesProblem(StatusCodes.Status404NotFound);

        // Bulk answers. Under /bulk for the reason the applications routes are: "bulk" is not a
        // Guid, so the single-reminder routes above can never catch these. Every one takes the
        // same selection — the ticked ids, or "all" with the count the user was shown — and every
        // one answers 409 when that count no longer holds, having changed nothing.
        const string countMismatchNote = " Returns 409 when an all selection no longer matches the count the caller " +
                                         "was shown; nothing is changed in that case.";

        group.MapPost("/bulk/dismiss", async (BulkReminderRequest request, ClaimsPrincipal user, IReminderService service,
                IStringLocalizer<SharedStrings> localizer, CancellationToken cancellationToken) =>
            {
                try
                {
                    return Results.Ok(await service.BulkDismissAsync(user.GetUserId(), request, cancellationToken));
                }
                catch (BulkCountMismatchException mismatch)
                {
                    return CountMismatchProblem(mismatch, localizer);
                }
            })
            .WithValidation<BulkReminderRequest>()
            .WithSummary("Dismiss many reminders at once")
            .WithDescription("Ids that are not the caller's or are already closed are ignored, not errors." + countMismatchNote)
            .Produces<BulkReminderResponse>()
            .Produces<BulkCountMismatch>(StatusCodes.Status409Conflict);

        group.MapPost("/bulk/follow-up", async (BulkReminderRequest request, ClaimsPrincipal user, IReminderService service,
                IStringLocalizer<SharedStrings> localizer, CancellationToken cancellationToken) =>
            {
                try
                {
                    return Results.Ok(await service.BulkMarkFollowedUpAsync(user.GetUserId(), request, cancellationToken));
                }
                catch (BulkCountMismatchException mismatch)
                {
                    return CountMismatchProblem(mismatch, localizer);
                }
            })
            .WithValidation<BulkReminderRequest>()
            .WithSummary("Answer many reminders with \"I followed up\"")
            .WithDescription("One FollowUpSent event per application behind the selection, every selected reminder closed." +
                             countMismatchNote)
            .Produces<BulkReminderResponse>()
            .Produces<BulkCountMismatch>(StatusCodes.Status409Conflict);

        group.MapPost("/bulk/ghost", async (BulkReminderRequest request, ClaimsPrincipal user, IReminderService service,
                IStringLocalizer<SharedStrings> localizer, CancellationToken cancellationToken) =>
            {
                try
                {
                    return Results.Ok(await service.BulkMarkGhostedAsync(user.GetUserId(), request, cancellationToken));
                }
                catch (BulkCountMismatchException mismatch)
                {
                    return CountMismatchProblem(mismatch, localizer);
                }
            })
            .WithValidation<BulkReminderRequest>()
            .WithSummary("Answer many reminders with \"it was ghosted\"")
            .WithDescription("Moves the open applications behind the selection to Ghosted, which closes their reminders. " +
                             "The response is a bulk status change's, and POST /bulk/ghost/undo takes it back." + countMismatchNote)
            .Produces<BulkChangeStatusResponse>()
            .Produces<BulkCountMismatch>(StatusCodes.Status409Conflict);

        group.MapPost("/bulk/ghost/undo", async (UndoBulkStatusRequest request, ClaimsPrincipal user,
                IApplicationService service, CancellationToken cancellationToken) =>
                Results.Ok(await service.UndoGhostAsync(user.GetUserId(), request, cancellationToken)))
            .WithValidation<UndoBulkStatusRequest>()
            .WithSummary("Undo answering reminders with \"it was ghosted\"")
            .WithDescription("Same compare-and-set as POST /api/applications/bulk/status/undo, without its size ceiling: the " +
                             "batch was resolved from the caller's own reminders, never from a client-chosen filter.")
            .Produces<UndoBulkStatusResponse>();

        return app;
    }

    /// <summary>Same shape as ApplicationEndpoints' 409 — same error code, both counts as extensions
    /// so the card can say which way the list moved and refresh itself — with a sentence that counts
    /// reminders rather than applications.</summary>
    private static IResult CountMismatchProblem(BulkCountMismatchException mismatch, IStringLocalizer<SharedStrings> localizer) =>
        Results.Problem(
            detail: localizer["REMINDER_COUNT_MISMATCH", mismatch.ActualCount],
            statusCode: StatusCodes.Status409Conflict,
            title: "Conflict",
            extensions: new Dictionary<string, object?>
            {
                ["errorCode"] = mismatch.ErrorCode,
                ["expectedCount"] = mismatch.ExpectedCount,
                ["actualCount"] = mismatch.ActualCount
            });
}
